### PR TITLE
not-reviewed interfaces are removed

### PR DESCRIPTION
**Pull request by nasibehteimouri**
Removed all not-reviewed interfaces!

### CODE REVIEW

**Comment by naved001** [comment]
@xuhang57 this is weird, see how pycodestyle failed when there was no input to it.

I would approve this if we fix pycodestyle on this. Once this is merged @nasibehteimouri you can rebase all your other PRs so that the diff is better.

**Comment by xuhang57** [comment]
And I don't think this PR is necessary since in other @nasibehteimouri 's PRs, interface files have been deleted. We could safely close this PR and work on the others.

**Comment by naved001** [comment]
Let's just review one of the other PRs, and once we merge that she can rebase the other ones. I vote to close this rather than having a one check for pylint to ignore the case where there are no python files. @chemistry-sourabh @apoorvemohan

**Comment by chemistry-sourabh** [comment]
Rebasing this PR should fix it as there is setup.py and \_\_init\_\_.py in the new folder structure

**Pull request merged**
