### PR TITLE
Changed Folder Structure

### PR DESCRIPTION
**Pull request by chemistry-sourabh**
Fixes Issue #6

Stuff done
1. Added gitignore
2. Added dev folder for developer scripts like setup dev environment, run tests, etc.
3. Added docker folder for any files required when creating container images.
4. Added driver folder for driver implementations.
5. Added m2 python package and did following stuff in it.
     a. Added database package
     b. Moved interface package
     c. Added core.py, rest.py and utils.py
6. Added unit, integration and stress folders in test folder (renamed)
7. Added empty Dockerfile for creating containers in future.
8. Added empty setup.py for installing.

I renamed all folders with plural names to singular names to follow some convention.

### CODE REVIEW

**Comment by xuhang57** [comment]
Thanks Dan for pointing it out.

So, should we use `tests` rather than `test`? since we have different types of tests.

**Comment by chemistry-sourabh** [comment]
@xuhang57 I called it "test" to have consistent convention for naming folders, which is to use the singular name instead of the plural name.

**Comment by chemistry-sourabh** [comment]
@naved001 The __ init __.py is for making the folder a python package. Just added it before hand to denote it.

Also which .txt files are you taking about ?

**Comment by xuhang57** [comment]
@chemistry-sourabh I don't have a strong opinion tbh. But speaking of the convention, do we have a doc/readme of what convention we are following? So in the future, we could have the references.

I normally use http://docs.python-guide.org/en/latest/writing/structure/ and it accepts both tests/test. But for the directories within the `test/tests`, it uses `/benchmarks rather than `/stress`.

**Comment by chemistry-sourabh** [comment]
Cool I'll have a read and rename stuff. We can follow the guide if no one has any objections.

**Pull request closed without merging**
